#!highlight yaml

heat_template_version: 2013-05-23

parameters:

  monitoring_vm_image:
    type: string
    label: monitoring_vm_image
    description: Name of the image for the monitoring VMs
    default: 'cirros'

  monitoring_vm_flavor:
    type: string
    label: monitoring_vm_flavor
    description: Name of the flavor for the monitoring VMs
    default: 'm1.tiny'

  monitoring_ip_pool:
    type: string
    label: monitoring_ip_pool
    description: IP Pool used for the Monitoring tier
    default: '172.2.0.0/24'

  monitoring_rule_set_name:
    type: string
    label: monitoring_rule_set_name
    description: Name of the Monitoring PRS
    default: 'Monitoring'

resources:

#### Network Setup ####

# Create L3 Policy for the IT 
    it_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: "IT"
            ip_pool: { get_param: monitoring_ip_pool }
            shared: False

# Create L2 Policies (Bridge Domains)
    monitoring_tier_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: it_l3_policy
        properties:
            name: "Monitoring Network"
            l3_policy_id: { get_resource: it_l3_policy }
            shared: False

#### Policy Classifiers, Actions, Rules Setup ####

# Create allow action
    allow_action:
        type: OS::Neutron::PolicyAction
        properties:
            name: "Allow"
            action_type: allow
            shared: True

# Create a classifier for monitoring traffic
    monitoring_classifier:
        type: OS::Neutron::PolicyClassifier
        properties:
            name: "Monitoring traffic"
            protocol: tcp
            port_range: '8080'
            direction: in
            shared: True

    monitoring_traffic_rule:
        type: OS::Neutron::PolicyRule
        depends_on: [ monitoring_classifier, allow_action ]
        properties:
            name: "Monitoring traffic"
            policy_classifier_id: { get_resource: monitoring_classifier }
            policy_actions: [{ get_resource: allow_action }]
            shared: True

#### Policy-Rules-Sets (Contracts) Setup ####

# Create Monitoring policy rule set
    monitoring_rule_set:
        type: OS::Neutron::PolicyRuleSet
        depends_on: monitoring_traffic_rule
        properties:
            name: { get_param: monitoring_rule_set_name }
            policy_rules: [{ get_resource: monitoring_traffic_rule }] 
            child_policy_rule_sets: []
            shared: True

#### Monitoring Tier ####

    monitoring_ptg:
        type: OS::Neutron::PolicyTargetGroup
        depends_on: [ monitoring_rule_set, monitoring_tier_l2_policy ]
        properties:
            name: "Monitoring Tier"
            l2_policy_id: { get_resource: monitoring_tier_l2_policy }
            provided_policy_rule_sets: 
                - policy_rule_set_id: { get_resource: monitoring_rule_set }
                  policy_rule_set_scope: 
            shared: False

    monitoring_server_pt1:
        type: OS::Neutron::PolicyTarget
        depends_on: monitoring_ptg
        properties:
            name: monitoring_server_pt1
            policy_target_group_id: { get_resource: monitoring_ptg }

    monitoring_server1:
        type: OS::Nova::Server
        depends_on: monitoring_server_pt1
        properties:
            name: Monitoring_Server
            image: { get_param: monitoring_vm_image }
            flavor: { get_param: monitoring_vm_flavor }
            networks:
                - port: {get_attr: [monitoring_server_pt1, port_id]}
