#!highlight yaml

heat_template_version: 2013-05-23

parameters:

  external_network_cidr:
    type: string
    label: external_network_cidr
    description: CIDR of external network
    default: '203.0.113.0/24'

  external_network_gateway:
    type: string
    label: external_network_gateway
    description: Gateway for external network
    default: '203.0.113.1'

  external_segment_name:
    type: string
    label: external_segment_name
    description: Name for external segment
    default: 'default'

  external_ptg_name:
    type: string
    label: external_ptg_name
    description: Name of the External Policy
    default: 'Outside'

  physical_network_name:
    type: string
    label: physical_network_name
    description: Name of the Physical network to map the external network to
    default: 'default'

  physical_network_type:
    type: string
    label: physical_network_type
    description: Flat or VLAN
    default: 'flat'

  port_address_translation:
    type: string
    label: port_address_translation
    description: True for Neutron rendering, False for APIC rendering
    default: 'False'

#  external_allocation_pool_start:
#    type: string
#    label: external_allocation_pool_start
#    description: Allocation pool start IP address 

#  external_allocation_pool_end:
#    type: string
#    label: external_allocation_pool_end
#    description: Allocation pool end IP address 

resources:

    external_network:
      type: OS::Neutron::Net
      properties:
        name: 'External Network'
        shared: True
        value_specs: {
            'router:external': True,
            'provider:physical_network': { get_param: physical_network_name },
            'provider:network_type': { get_param: physical_network_type }
        }

    external_subnet:
      type: OS::Neutron::Subnet
      properties:
        name: 'External_Subnet'
        network_id: {get_resource: external_network}
        cidr: {get_param: external_network_cidr}
        gateway_ip: {get_param: external_network_gateway}
#        allocation_pools: [{
#          "start": {get_param: external_allocation_pool_start},
#          "end": {get_param: external_allocation_pool_end}
#        }]

    external_segment:
        type: OS::Neutron::ExternalSegment
        properties:
            name: { get_param: external_segment_name }
            port_address_translation: { get_param: port_address_translation }
            subnet_id: { get_resource: external_subnet }
            external_routes:
                - destination: '0.0.0.0/0'
                  nexthop:
            shared: True

    external_ptg:
        type: OS::Neutron::ExternalPolicy
        properties:
            name: { get_param: external_ptg_name }
            external_segments: [ { get_resource: external_segment } ]
            shared: False
